version: "3.1"

services:
  nginx:
    ports:
      - 8881:80
    image: "nginx:latest"
    platform: "linux/arm64/v8"
    volumes:
      - ../out:/app/static
      - ./nginx.conf:/etc/nginx/nginx.conf